services:
  frontend:
    environment:
      NODE_ENV: 'production'
      VITE_BACKEND_BASEURL: ${VITE_BACKEND_BASEURL}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_BASEURL=${VITE_BACKEND_BASEURL}
    image: ngzm/iine-frontend:1.1.10
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
