version: '3.8'

services:
  frontend:
    environment:
      VITE_BACKEND_BASEURL: ${VITE_BACKEND_BASEURL}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_BASEURL=${VITE_BACKEND_BASEURL}
    image: ngzm/iine-frontend:test-0.0.1
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
